hiddengems/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('maps/', views.maps, name='maps'),
  path('gems/', views.gems_index, name='index'),
  path('accounts/signup/', views.signup, name='signup'),
  path('gems/<int:gem_id>/', views.gems_detail, name='detail'),
  path('gems/create/', views.GemCreate.as_view(), name='gems_create'),
  path('gems/<int:pk>/update/', views.GemUpdate.as_view(), name='gems_update'),
  path('gems/<int:pk>/delete/', views.GemDelete.as_view(), name='gems_delete'),
  path('gems/<int:gem_id>/add_photo/', views.add_photo, name='add_photo'),
  path('photo/<int:pk>/delete/', views.PhotoDelete.as_view(), name='photo_delete'),
  path('gems/<int:gem_id>/add_review/', views.add_review, name='add_review'),
  path('review/<int:pk>/delete/', views.ReviewDelete.as_view(), name='delete_review'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

CATEGORIES = (
    ('B', 'Business'),
    ('T', 'Trail'),
    ('R', 'Ruins'),
    ('L', 'Landmark'), 
)

class Gem(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    latitude = models.FloatField(max_length=100)
    longitude = models.FloatField(max_length=100)
    description = models.TextField(max_length=300)
    category = models.CharField(
        max_length=1,
        choices=CATEGORIES,
        default=CATEGORIES[0][0],
        )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{ self.name } ({ self.id })"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'gem_id': self.id})

RATINGS = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
)

class Review(models.Model):
    content = models.TextField(max_length=300)
    rating = models.IntegerField(
        choices=RATINGS,
        default=RATINGS[4][0]
    )
    gem = models.ForeignKey(Gem, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_rating_display()}"

class Photo(models.Model):
    url = models.CharField(max_length=200)
    gem = models.ForeignKey(Gem, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for gem_id: {self.gem_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Review, Photo

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['content', 'rating']

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ['url', 'gem']

main_app/views.py
import os
from re import template
import boto3
import uuid
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Gem, Review, Photo
from .forms import ReviewForm


# Define the home view
def home(request):
    return render(request, 'base.html')

@login_required
def maps(request):
  gems = Gem.objects.all()
  mapbox_access_token = os.environ['MAP_KEY']
  return render(request, 'gems/maps.html', 
    { 'MAP_KEY' : mapbox_access_token, 'gems': gems })

def gems_index(request):
  gems = Gem.objects.all
  return render(request, 'gems/index.html', {'gems': gems})

@login_required
def gems_detail(request, gem_id):
  gem = Gem.objects.get(id=gem_id)
  review_form = ReviewForm()
  return render(request, 'gems/detail.html', {
    'gem': gem, 'review_form': review_form, 'MAP_KEY': os.environ['MAP_KEY']
  })

class GemCreate(LoginRequiredMixin, CreateView):
  model = Gem
  fields = ['name', 'location', 'latitude', 'longitude', 'description', 'category']
  success_url = '/gems/'

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class GemUpdate(LoginRequiredMixin, UpdateView):
  model = Gem
  fields = ['location', 'latitude', 'longitude', 'description', 'category']

class GemDelete(LoginRequiredMixin, DeleteView):
  model = Gem
  success_url = '/gems/'

@login_required
def add_review(request, gem_id):
  form = ReviewForm(request.POST)
  if form.is_valid():
    new_review = form.save(commit=False)
    new_review.gem_id = gem_id
    new_review.save()
  return redirect('detail', gem_id=gem_id)

class ReviewDelete(LoginRequiredMixin, DeleteView):
  model = Review
  template = "/main_app/_confirm_delete.html"
  success_url = '/gems/'

def add_photo(request, gem_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            Photo.objects.create(url=url, gem_id=gem_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', gem_id=gem_id)

class PhotoDelete(LoginRequiredMixin, DeleteView):
  model = Photo
  # template = "/main_app/photo_confirm_delete.html"
  success_url = '/gems/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def some_function(request):
  secret_key = os.environ['SECRET_KEY']

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Hidden Gems</title>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js'></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">  <link href="https://fonts.googleapis.com/css?family=Londrina+Sahdow" rel="stylesheet" type="text/css">
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.css' rel='stylesheet' />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
  <body class="d-flex flex-column min-vh-100">
    <div class="container-fluid g-0">
      <div class="row">
        <div class="container-fliud">
          <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="https://imgur.com/MNil7y4.png" class="d-block w-100" alt="..." style="object-fit: cover; width: 100%; height: 100%;">
              </div>
              <div class="carousel-item">
                <img src="https://imgur.com/FHfoCLD.png" class="d-block w-100" alt="..." style="object-fit: cover; width: 100%; height: 100%;">
              </div>
              <div class="carousel-item">
                <img src="https://imgur.com/kKGA19V.png" class="d-block w-100" alt="..." style="object-fit: cover; width: 100%; height: 100%;">
              </div>
              <div class="carousel-item">
                <img src="https://imgur.com/iJo4HMh.png" class="d-block w-100" alt="..." style="object-fit: cover; width: 100%; height: 100%;">
              </div>
              <div class="carousel-item">
                <img src="https://imgur.com/83mIPqe.png" class="d-block w-100" alt="..." style="object-fit: cover; width: 100%; height: 100%;">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
        </div>
      </div>
        <header class="navbar-fixed">
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <img src= "https://i.imgur.com/kNKtlxn.png" style="height: 50px; object-fit:cover">
              <a href="/" class="navbar-brand">&nbsp;&nbsp;HiddenGemsUSA</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                <ul class="navbar-nav">
                  <li><a class="dropdown-item" style="color:grey" href="{% url 'index' %}">View Hidden Gems</a></li>
                  <li><a class="dropdown-item" style="color:grey" href="{% url 'maps' %}">Map</a></li>
                  {% if user.is_authenticated %}
                  <li><a class="dropdown-item" style="color:grey" href="{% url 'gems_create' %}">Create Gem</a></li>
                  <li><a class="dropdown-item" style="color:grey" href="{% url 'logout' %}">Log Out</a></li>
                  {% else %}
                    <li><a class="dropdown-item" style="color:grey" href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a class="dropdown-item" style="color:grey" href="{% url 'login' %}">Log in</a></li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
        </header>
        <main class="">
          {% block content %}
          <br>
          <br>
          <h1 class="text-center">Welcome to Hidden Gems</h1>

          <img class="text-center" src="" alt="">

          <hr />
          <div class="text-center">
            <p>Hidden Gems is designed to connect adventures to awesome secret places. A place to share and review your favorite hidden gems, from restaurants, to lookouts, to ruins.</p>
            <p>Sign in to share your hidden gem!</p>
          </div>
          
          {% endblock %}
        </main>  
      </div>
    </div>
  </div>
</body>
<br>
<footer class="bg-dark text-center text-white mt-auto">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright
    <a class="text-white" href="">Hidden Gems<img src= "https://i.imgur.com/kNKtlxn.png" style="height: 50px; object-fit:cover"></a>
  </div>
</footer>
</html>

main_app/templates/gems/detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center">Gem Details</h1>

<div class="card">
  {% for photo in gem.photo_set.all %}
    <div class="text-center">
      <img class="card-img-top border border-2 border-secondary" src="{{photo.url}}" style="width: 600px;">
    </div>
  {% empty %}
    <div class="text-center">
      <img class="card-img-top border border-2 border-secondary" style="width: 600px;" src="https://i.imgur.com/5EzN5dq.png">
    </div>
  {% endfor %}
    <div class="d-flex flex-column bd-highlight mb-3">
      <form action="{% url 'add_photo' gem.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
        {% csrf_token %}
        {% if user == gem.user %}
          <div class="text-center">
            <input class="btn btn-outline-secondary" type="file" name="photo-file">
          </div>
          <div class="text-center">
            <button class="btn btn-outline-secondary" type="submit">Upload Photo</button>
          </div>
        {% endif %}
      </form>
      {% if user == gem.user %}
        {% for photo in gem.photo_set.all %}
          <div class="text-center">
            <a class="btn btn-outline-danger" href="{% url 'photo_delete' photo.id %}">Delete</a>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
  <div class="card">
    <div class ="card-content">
        <span class="card-title"> &nbsp&nbsp&nbsp {{gem.name}}</span>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Location: {{ gem.location }}</li>
          <li class="list-group-item">Latitude: {{ gem.latitude }}</li>
          <li class="list-group-item">Longitude: {{ gem.longitude }}</li>
          <li class="list-group-item">Description: {{ gem.description }}</li>
          <li class="list-group-item">Category: {{ gem.get_category_display }}</li>
        </ul>
    </div>
      <div class="text-center">
        {% if user == gem.user %}
            <a class="btn btn-outline-secondary" href="{% url 'gems_update' gem.id %}">Edit Gem</a>
            <a class="btn btn-outline-danger" href="{% url 'gems_delete' gem.id %}">Delete Gem</a>
        {% endif %}
      </div> 
</div> 

<div class="d-flex justify-content-center">
  <div class="border border-secondary border-3 w-75"id='map' width="100%" style='height:400px'></div>
</div>
<br>
<div class="container">
    <h1 class="row d-flex justify-content-center">Add Review</h1>
    <form class="row" action="{% url 'add_review' gem.id %}" method="POST">
        {% csrf_token %}
        <div class="d-flex flex-row bd-highlight align-items-end justify-content-center">
          {{ review_form.as_p }}
        </div>
        <div class="d-flex justify-content-center">
          <button class="btn btn-outline-secondary w-25" type="submit">Add Review</button>
        </div>
        &nbsp;
        <hr>
        <br>
    </form>
    <div class="row">
      <h4 class="col">Reviews</h4>
      <h4 class="col d-flex flex-row bd-highlight">Ratings</h4>
    </div>
    {% for review in gem.review_set.all %}
    <div class="row">
      <div class="col d-flex justify-content-evenly border border-secondary border-1 rounded">{{ review.content }}</div>
      <div class="col d-flex flex-row bd-highlight"> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ review.get_rating_display }}</div>
    {% if user == review.user %}
      <a class="col btn btn-outline-danger" style="max-width: 70px;" href="{% url 'delete_review' review.id %}">Delete</a>
    {% endif %}
    </div>   
    {% endfor %}
  </div>
<script>
  mapboxgl.accessToken = '{{ MAP_KEY }}'
  var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v10',
      center: [{{ gem.longitude }}, {{ gem.latitude }}], // Starting position [lng, lat]
      zoom: 10, // Starting zoom level
  });
  const marker = new mapboxgl.Marker() // initialize a new marker
      .setLngLat([{{ gem.longitude }}, {{ gem.latitude }}]) // Marker [lng, lat] coordinates
      .addTo(map); // Add the marker to the map
</script>
{% endblock %}

main_app/templates/gems/index.html
{% extends 'base.html' %}
{% block content %}
<br>
<h1 class="text-center">Hidden Gems</h1>
{% for gem in gems %}
  <div class="d-inline-flex p-2 bd-highlight">
    <div class="card border border-dark border-2" style="width: 18rem;">
      {% for photo in gem.photo_set.all %}
        <img class="card-img-top center-align" style="height: 200px;" src="{{photo.url}}">
      {% empty %}
        <img src="https://i.imgur.com/5EzN5dq.png" class="card-img-top center-align" style="height: 200px;">
      {% endfor %}
      <div class="card-body text-center">   
        <h3 class="card-title">{{ gem.name }}</h3>
      </div>
      <div class="text-center"> 
        <p class="card-text">Location: {{ gem.location }}</p>
      </div>
      <br>
      <a class="btn btn-primary" href="/gems/{{ gem.id }}">See Details</a>
    </div>
  </div>

{% endfor %}

{% endblock %}

main_app/templates/gems/map.html
{% extends 'base.html' %}
{% block content %}
    <h1>Map time!</h1>
    <div id='map' width="100%" style='height:400px'></div>
    <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoibWlrZW5vdmEiLCJhIjoiY2t6ajF0ZHd2MDVrMjJvbXE2OG0xbDg3NCJ9.q_wwOsFi-0Pbyhx5ESJfTg'
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v10'
        });
    </script>
{% endblock %}

main_app/templates/gems/maps.html
{% extends 'base.html' %}
{% block content %}
<br>
<h1 class="text-center" style="text-decoration-line: underline;">Time To Explore!</h1>
<div class="d-flex justify-content-center">
    <div class="border border-secondary border-3 w-75" id='map' width="100%" style='height:400px;'></div>
</div>
<script>
    mapboxgl.accessToken = '{{ MAP_KEY }}'
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v10',
        center: [-111.8910, 40.7608], // Starting position [lng, lat]
        zoom: 3, // Starting zoom level
    });

    const gems = [
        {% for gem in gems %}
            {lat: {{ gem.latitude}}, lng: {{ gem.longitude }}, name: "{{ gem.name }}" },
        {% endfor %}
    ];
    gems.forEach(function(gem) {
        new mapboxgl.Marker()
        .setLngLat([gem.lng, gem.lat]).addTo(map)
        .setPopup(
            new mapboxgl.Popup({offset: 5})
                .setHTML(
                    `<h5>${gem.name}</h5>`
                )
        );
    })
</script>
{% endblock %}

main_app/templates/main_app/gem_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Gem</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' gem.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/gem_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
<br>
  <h1 class="text-center">Create A Gem</h1>
{% endif %}
<div class="text-center">
<form action="" method="POST">
  {% csrf_token %}
  <table class="table table-light table-hover">
    {{ form.as_table }}
  </table>
  <button class="btn btn-outline-secondary" id="locationbtn" disabled>Use Current Location</button>
  <input type="submit" value="Submit!" class="btn btn-outline-secondary">
</form>
</div>
<script>
  const btn = document.getElementById('locationbtn');
  const latEl = document.getElementById('id_latitude');
  const lngEl = document.getElementById('id_longitude');
  let lat, lng;
  navigator.geolocation.getCurrentPosition(function(result){
    btn.disabled = false;
    lat = result.coords.latitude;
    lng = result.coords.longitude;
  })
  btn.addEventListener('click', function(evt){
    evt.preventDefault();
    latEl.value = lat;
    lngEl.value = lng;
  })
</script>
  {% endblock %}

main_app/templates/main_app/photo_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Photo</h1>

  <h4>Are you sure you want to delete <span class="teal-text">Your Photo</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.gem.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/review_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Review</h1>

  <h4>Are you sure you want to delete <span class="teal-text">Your Review</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.gem.id %}">Cancel</a>
  </form>
{% endblock %}